# Generated by Django 4.0.1 on 2022-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('agenda', '0002_updownhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tags',
            field=models.ManyToManyField(related_name='agendas', to='tag.Tag'),
        ),
    ]
