# Generated by Django 4.0.1 on 2022-02-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agenda_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updownhistory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updown_history', to='agenda.agenda'),
        ),
    ]
