# Generated by Django 4.0.1 on 2022-03-07 17:46

import discuss_api.apps.agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_vote_created_time_vote_updated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DELETED_BY_USER', 'deleted_by_user'), ('DELETED_BY_ADMIN', 'deleted_by_admin'), ('DELETED_BY_WITHDRAWAL', 'deleted_by_withdrawal')], default=discuss_api.apps.agenda.models.CommentStatus['ACTIVE'], max_length=25),
        ),
    ]
