# Generated by Django 4.0.6 on 2023-02-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementhistory',
            name='value',
            field=models.CharField(choices=[('AGREE', 'agree'), ('DISAGREE', 'disagree')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updownhistory',
            name='updown',
            field=models.CharField(choices=[('UP', 'up'), ('DOWN', 'down'), ('NONE', 'None')], max_length=20),
        ),
    ]
