# Generated by Django 4.0.6 on 2023-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agreementhistory_value_alter_updownhistory_updown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('AGREE', 'agree'), ('VERY_AGREE', 'very_agree'), ('DISAGREE', 'disagree'), ('VERY_DISAGREE', 'very_disagree'), ('NEUTRAL', 'neutral')], max_length=20),
        ),
    ]
