# Generated by Django 4.0.2 on 2022-11-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_profilepicture_userprofile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
