name: "Deploy"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Authenticate Google
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: discuss-nez
      - run: |
          gcloud builds submit --tag=gcr.io/discuss-nez/api
          gcloud run deploy api --image=gcr.io/discuss-nez/api --region=asia-northeast3
